# Generated by Django 4.2.4 on 2023-09-15 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0002_rename_enquirydate_enquiry_enquirydate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='emailaddres',
            new_name='emailaddress',
        ),
    ]
